version: '3'
services:
  db:
    image: postgres:13.2-alpine
    network_mode: bridge
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: walking_duck
    ports:
      - 5432:5432
  redis:
    image: redis:7.0.12-alpine
    network_mode: bridge
    ports:
      - 6379:6379
  node:
    build: 
      context: ./
      dockerfile: ./docker/node.Dockerfile
    volumes:
      - ./node:/opt/app
    network_mode: bridge
    env_file: ./env
    environment:
      - NODE_ENV=dev
    depends_on:
      - db
      - redis
    ports:
      - 8092:80
  python:
    build: 
      context: ./
      dockerfile: ./docker/python.Dockerfile
    volumes:
      - ./python:/opt/app
    network_mode: bridge
    env_file: ./env
    environment: 
      - PYTHON_ENV=dev
    depends_on:
      - db
      - redis
    ports:
      - 8091:80
  rust:
    build: 
      context: ./
      dockerfile: ./docker/rust.Dockerfile
    volumes:
      - ./rust:/opt/app
    network_mode: bridge
    env_file: ./env
    environment:
      - RUST_ENV=dev
      - RUST_LOG=debug
    depends_on:
      - db
      - redis
    ports:
      - 8090:80